/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article/Article.vue')['default']
    Aside: typeof import('./src/components/aside/Aside.vue')['default']
    AsideDirectory: typeof import('./src/components/aside/AsideDirectory.vue')['default']
    Avatar: typeof import('./src/components/aside/Avatar.vue')['default']
    Category: typeof import('./src/components/category/Category.vue')['default']
    CategoryArticle: typeof import('./src/components/category/CategoryArticle.vue')['default']
    CategoryLine: typeof import('./src/components/index/CategoryLine.vue')['default']
    ChildContent: typeof import('./src/components/comment/ChildContent.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommentContent: typeof import('./src/components/comment/CommentContent.vue')['default']
    CommentSubmit: typeof import('./src/components/comment/CommentSubmit.vue')['default']
    CopyRight: typeof import('./src/components/article/CopyRight.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    Essay: typeof import('./src/components/essay/Essay.vue')['default']
    EssayPage: typeof import('./src/components/essay/EssayPage.vue')['default']
    Footer: typeof import('./src/components/foot/Footer.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    NavBar: typeof import('./src/components/head/NavBar.vue')['default']
    PreAndNextArticle: typeof import('./src/components/article/PreAndNextArticle.vue')['default']
    RecentPost: typeof import('./src/components/index/RecentPost.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/index/Swiper.vue')['default']
    Tag: typeof import('./src/components/tag/Tag.vue')['default']
    TagArticle: typeof import('./src/components/tag/TagArticle.vue')['default']
    TreeHoles: typeof import('./src/components/treeHoles/TreeHoles.vue')['default']
  }
}
